services:
  - type: web
    name: election-system
    env: python
    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
    startCommand: gunicorn election_system.wsgi:application --bind=0.0.0.0:10000
    envVars:
      - key: PORT
        value: 10000
      - key: PYTHON_VERSION
        value: 3.13.0
      - key: DJANGO_SETTINGS_MODULE
        value: election_system.settings.production
      - key: USE_I18N
        value: true
      - key: LANGUAGE_CODE
        value: es
      # Optional: set these to add your custom domain(s) without code changes
      # - key: EXTRA_ALLOWED_HOSTS
      #   value: tu-dominio.com,www.tu-dominio.com
      # - key: EXTRA_CSRF_TRUSTED_ORIGINS
      #   value: https://tu-dominio.com,https://www.tu-dominio.com
    buildFilter:
      paths:
      - requirements.txt
      - "**/*.py"
      - "**/*.html"
  - "**/*"
