# Generated by Django 5.1.7 on 2025-03-24 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0002_alter_clientprofile_visitor_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientprofile',
            name='organization_name',
            field=models.CharField(default='radicales', max_length=255),
        ),
    ]
