# Generated by Django 5.1.7 on 2025-04-05 21:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0003_clientprofile_organization_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='clientprofile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='voter',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voters', to='voting.clientprofile'),
        ),
        migrations.DeleteModel(
            name='Visitor',
        ),
    ]
