# Generated by Django 5.1.7 on 2025-10-20 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0007_replace_zone_index_with_partial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voter',
            name='dni',
            field=models.CharField(max_length=20),
        ),
        migrations.AddConstraint(
            model_name='voter',
            constraint=models.UniqueConstraint(fields=('client', 'dni'), name='voter_client_dni_uniq'),
        ),
    ]
