# Generated by Django 5.1.7 on 2025-10-22 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0008_alter_voter_dni_voter_voter_client_dni_uniq'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientprofile',
            name='total_voters',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='voted_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='zone',
            name='total_voters',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='zone',
            name='voted_count',
            field=models.IntegerField(default=0),
        ),
    ]
