# Generated by Django 5.1.7 on 2025-10-26 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0009_clientprofile_total_voters_clientprofile_voted_count_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voter',
            name='name',
        ),
        migrations.AddField(
            model_name='voter',
            name='address',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='voter',
            name='establecimiento',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='voter',
            name='first_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='voter',
            name='last_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='voter',
            name='mesa',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='voter',
            name='orden',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='voter',
            name='sex',
            field=models.CharField(blank=True, default='', max_length=1),
        ),
        migrations.AddIndex(
            model_name='voter',
            index=models.Index(condition=models.Q(('voted', False)), fields=['client', 'zone', 'mesa', 'orden'], name='voter_cz_mo_notv'),
        ),
    ]
